extentions:
  application_ext: hi
  icon_valid_ext:
  - .png
  module_valide_ext:
  - .py
regex:
  module_file_sanity_name: hi_(.*)\..*
sources:
- C:\Users\youssef\Documents\GitHub\Helpers-Interface\python\scripts
