sources:
- 'C:\Users\youss\Documents\GitHub\Maya-Helper-Interface\python\scripts'

icon_valid_ext:
- '.png'

module_valide_ext:
- '.py'

application_ext: 'hi'

regex:
  module_file_sanity_name : '.*_.*\..*'